{ stdenv, fetchurl, python, asciidoc, re2c }:

stdenv.mkDerivation rec {
  name = "ninja-${version}";
  version = "1.8.2.g3bbbe.kitware.dyndep-1.jobserver-1";

  src = fetchurl {
    url = "https://github.com/Kitware/ninja/archive/v${version}.tar.gz";
    sha256 = "0ba81ngdl89ix997c3kgdi2chaj4h5m2a6m762ksxj1jxhn4670j";
  };

  buildInputs = [ python asciidoc re2c ];

  buildPhase = ''
    python configure.py --bootstrap
    asciidoc doc/manual.asciidoc
  '';

  installPhase = ''
    install -Dm555 -t $out/bin ninja
    install -Dm444 -t $out/share/doc/ninja doc/manual.asciidoc doc/manual.html
    install -Dm444 misc/bash-completion $out/share/bash-completion/completions/ninja
    install -Dm444 misc/zsh-completion $out/share/zsh/site-functions/_ninja
  '';

  setupHook = ./setup-hook.sh;

  meta = with stdenv.lib; {
    description = "Small build system with a focus on speed";
    longDescription = ''
      Ninja is a small build system with a focus on speed. It differs from
      other build systems in two major respects: it is designed to have its
      input files generated by a higher-level build system, and it is designed
      to run builds as fast as possible.
      Kitware maintains this branch of Ninja in order to provide features
      needed to support Fortran builds but that have not yet been integrated
      upstream.
    '';
    homepage = https://ninja-build.org/;
    license = licenses.asl20;
    platforms = platforms.unix;
    maintainers = with maintainers; [ robertodr ];
  };
}
